[project]
name = "visualising-with-seaborn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.2.5",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "pyodbc>=5.2.0",
    "seaborn>=0.13.2",
]
